import dataclasses
import pathlib

import beet


@dataclasses.dataclass
class Datapack:
    name: str
    description: str = "A Datapack generated by the mcutils_reborn module."
    pack_format: int = -2

    def export(self, path: pathlib.Path) -> beet.DataPack:
        out = beet.DataPack(
            name=self.name,
            path=path / self.name,
            zipped=False,
            description=self.description,
            pack_format=self.pack_format,
        )

        return out
